todo:
- Map KD, REV, Sub ATT to int
- process takedown attempts

ideas/notes:
- parse DETAILS column in fight data
    - can get judge scores and finish type
- add general parameterized load_if_exists function to utils to replace data loading functions in scrapers
- fighter stats with no data are recorded as "0" online, care
- derived fighter columns for
    - win streaks
    - ufc record
    - total record
    - champion/former champ status
- only pulling weight from fight data, not fighter data to account for people moving around divisions
    - would be nice to list all weights competed at/have missed weight marks, but weigh in weight isn't present on ufcstats
- reorg scraper class so that it makes more sense as a data entry point.

- including w/l/d/nc data for fighter biography, but take care using it
    - if used in training data, you really want their record at the time of the fight, not current
    - might be able to reverse engineer that from the fight data by counting their ufc fights, but this logic would mess up if there were gaps in someones ufc stint (eg fights in ufc, fights in other org, then fights back in ufc)

In [1]:
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd

# IMMEDIATELY CHANGE TO ROOT DIR
# ONLY RUN THIS ONCE/INCLUDED CODE TO RESTART KERNEL ON EXECUTE.
# POSSIBLY ONLY USE THIS CONTEXT MANAGER
import os
os.chdir('..')
print(os.getcwd())

# local imports once you're in the root
from src.ufctools.scraping import FightDataScraper
from src.ufctools.preprocess import process_fighter_data, process_fight_data

d:\code\frankie_edgar_stan_zone

In [2]:
scraper = FightDataScraper()
fight_df = scraper.fight_data
fighter_df = scraper.fighter_data

Pulling event data from http://ufcstats.com/statistics/events/completed?page=all
Reading local event data from d:\code\frankie_edgar_stan_zone\data\event_data.csv
No new events, local data up to date
Loading local fight links from d:\code\frankie_edgar_stan_zone\data\fight_links.pickle
Reading local raw fight data from d:\code\frankie_edgar_stan_zone\data\raw_fight_data.csv
Reading local raw fighter data from d:\code\frankie_edgar_stan_zone\data\raw_fighter_details.csv

In [3]:
# data scraped as of 11/26
scraper.scrape_new_fights()
scraper.update_fighter_data()

Checking for new events to scrape
Scraping fight links from 1 events:
Progress: |██████████████████████████████████████████████████| 100.00% Complete
Scraping fights from 1 event/s.

0it [00:00, ?it/s]

Updating fight data.
Saving fight data to d:\code\frankie_edgar_stan_zone\data\raw_fight_data.csv
Removing temporary files
Refreshing fighter data with fights from 2025-11-20 00:00:00 onwards.
Getting data for 28 fighters.

  0%|          | 0/28 [00:00<?, ?it/s]

Saving fighter data to d:\code\frankie_edgar_stan_zone\data\raw_fighter_details.csv

,FIGHTER_LINK,AS_OF_DATE,FIGHTER,WIN,LOSS,DRAW,NC,HEIGHT,WEIGHT,REACH,STANCE,DOB,SLPM,STR_ACC,SAPM,STR_DEF,TD_AVG,TD_ACC,TD_DEF,SUB_AVG
FIGHTER_ID,,,,,,,,,,,,,,,,,,,,
fb37795db81f93f3,http://ufcstats.com/fighter-details/fb37795db8...,2025-11-26,BOGDAN GRAD,15,4,0,0,"5' 8""",145 LBS.,"70""",ORTHODOX,"SEP 28, 1995",4.06,51%,5.06,49%,4.22,40%,75%,0.0
a4dc0f2b95df4cc1,http://ufcstats.com/fighter-details/a4dc0f2b95...,2025-11-26,BEKZAT ALMAKHAN,12,3,0,0,"5' 7""",135 LBS.,"68""",ORTHODOX,"OCT 08, 1997",1.61,34%,3.73,36%,0.00,0%,41%,0.0
98aa60cf58071fd6,http://ufcstats.com/fighter-details/98aa60cf58...,2025-11-26,KYOJI HORIGUCHI,35,5,0,1,"5' 4""",125 LBS.,"63""",ORTHODOX,"OCT 12, 1990",3.64,46%,2.26,62%,1.80,42%,54%,0.1
ab2b4ff41d6ebe0f,http://ufcstats.com/fighter-details/ab2b4ff41d...,2025-11-26,ALEX PEREZ,25,10,0,0,"5' 6""",125 LBS.,"65""",ORTHODOX,"MAR 21, 1992",4.16,45%,3.22,58%,2.28,48%,75%,0.8
52b6bf4528130e86,http://ufcstats.com/fighter-details/52b6bf4528...,2025-11-26,SHEM ROCK,12,2,1,0,"5' 11""",155 LBS.,"73""",SOUTHPAW,"NOV 05, 1993",2.93,42%,3.40,56%,1.00,11%,80%,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
a20d7dfaba74c067,http://ufcstats.com/fighter-details/a20d7dfaba...,2025-11-26,RODRIGO DAMM,13,9,0,0,"5' 7""",155 LBS.,"71""",ORTHODOX,"FEB 03, 1980",3.5,36%,5.61,57%,0.44,16%,80%,0.3
31652c9267606d54,http://ufcstats.com/fighter-details/31652c9267...,2025-11-26,JOHN LOBER,5,9,4,0,"5' 11""",199 LBS.,--,ORTHODOX,"FEB 26, 1968",0.0,0%,0.0,0%,0.0,0%,0%,0.0
86f582852a5b240a,http://ufcstats.com/fighter-details/86f582852a...,2025-11-26,MAC DANZIG,21,12,1,0,"5' 8""",155 LBS.,"70""",ORTHODOX,"JAN 02, 1980",3.39,48%,3.44,57%,1.2,37%,46%,0.6
ff6a1f63c254127e,http://ufcstats.com/fighter-details/ff6a1f63c2...,2025-11-26,ALBERT TUMENOV,18,4,0,0,"5' 11""",170 LBS.,"73""",ORTHODOX,"DEC 26, 1991",3.76,42%,3.34,58%,0.2,20%,75%,0.0
51b1e2fd9872005b,http://ufcstats.com/fighter-details/51b1e2fd98...,2025-11-26,MACKENS SEMERZIER,8,4,0,1,"5' 9""",145 LBS.,"72""",ORTHODOX,"NOV 03, 1980",2.91,45%,3.48,46%,2.14,50%,50%,2.1

In [ ]:
processed_fighter_data = process_fighter_data(scraper.fighter_data, save_local = True)
processed_fight_data = process_fight_data(scraper.fight_data, save_local = True)

Saving to d:\code\frankie_edgar_stan_zone\data\processed_fighter_details.csv

,FIGHTER_LINK,AS_OF_DATE,FIGHTER,WIN,LOSS,DRAW,NC,HEIGHT,WEIGHT,REACH,STANCE,DOB,SLPM,STR_ACC,SAPM,STR_DEF,TD_AVG,TD_ACC,TD_DEF,SUB_AVG
FIGHTER_ID,,,,,,,,,,,,,,,,,,,,
fb37795db81f93f3,http://ufcstats.com/fighter-details/fb37795db8...,2025-11-26,BOGDAN GRAD,15,4,0,0,68,145,70,ORTHODOX,1995-09-28,4.06,0.51,5.06,0.49,4.22,0.40,0.75,0.0
a4dc0f2b95df4cc1,http://ufcstats.com/fighter-details/a4dc0f2b95...,2025-11-26,BEKZAT ALMAKHAN,12,3,0,0,67,135,68,ORTHODOX,1997-10-08,1.61,0.34,3.73,0.36,0.00,0.00,0.41,0.0
98aa60cf58071fd6,http://ufcstats.com/fighter-details/98aa60cf58...,2025-11-26,KYOJI HORIGUCHI,35,5,0,1,64,125,63,ORTHODOX,1990-10-12,3.64,0.46,2.26,0.62,1.80,0.42,0.54,0.1
ab2b4ff41d6ebe0f,http://ufcstats.com/fighter-details/ab2b4ff41d...,2025-11-26,ALEX PEREZ,25,10,0,0,66,125,65,ORTHODOX,1992-03-21,4.16,0.45,3.22,0.58,2.28,0.48,0.75,0.8
52b6bf4528130e86,http://ufcstats.com/fighter-details/52b6bf4528...,2025-11-26,SHEM ROCK,12,2,1,0,71,155,73,SOUTHPAW,1993-11-05,2.93,0.42,3.40,0.56,1.00,0.11,0.80,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
a20d7dfaba74c067,http://ufcstats.com/fighter-details/a20d7dfaba...,2025-11-26,RODRIGO DAMM,13,9,0,0,67,155,71,ORTHODOX,1980-02-03,3.50,0.36,5.61,0.57,0.44,0.16,0.80,0.3
31652c9267606d54,http://ufcstats.com/fighter-details/31652c9267...,2025-11-26,JOHN LOBER,5,9,4,0,71,199,0,ORTHODOX,1968-02-26,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
86f582852a5b240a,http://ufcstats.com/fighter-details/86f582852a...,2025-11-26,MAC DANZIG,21,12,1,0,68,155,70,ORTHODOX,1980-01-02,3.39,0.48,3.44,0.57,1.20,0.37,0.46,0.6
ff6a1f63c254127e,http://ufcstats.com/fighter-details/ff6a1f63c2...,2025-11-26,ALBERT TUMENOV,18,4,0,0,71,170,73,ORTHODOX,1991-12-26,3.76,0.42,3.34,0.58,0.20,0.20,0.75,0.0
51b1e2fd9872005b,http://ufcstats.com/fighter-details/51b1e2fd98...,2025-11-26,MACKENS SEMERZIER,8,4,0,1,69,145,72,ORTHODOX,1980-11-03,2.91,0.45,3.48,0.46,2.14,0.50,0.50,2.1

d:\code\frankie_edgar_stan_zone\src\ufctools\preprocess.py:254: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  filtered_df = filtered_df.fillna(0)
d:\code\frankie_edgar_stan_zone\src\ufctools\preprocess.py:269: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(insert_loc, col_name, col_df[col_name])
d:\code\frankie_edgar_stan_zone\src\ufctools\preprocess.py:269: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(insert_loc, col_name, col_df[col_name])

In [4]:
processed_fight_data['R_SUB_ATT_R2']

FIGHT_ID
5f5b626e67529056    1
b2218930b982d9b6    0
870d374f8d9af65a    0
8ed609d80e135d94    0
e8307c7686c42d8c    0
                   ..
3b020d4914b44fc8    0
d917c8c7461b9831    0
ccee020be2e8d9f6    0
4b9ae533ccb3fcdf    0
4acab67848e78327    0
Name: R_SUB_ATT_R2, Length: 8447, dtype: int64

In [5]:
processed_fight_data.info(show_counts=True, verbose = True)

<class 'pandas.core.frame.DataFrame'>
Index: 8447 entries, 5f5b626e67529056 to 4acab67848e78327
Data columns (total 308 columns):
 #    Column                    Non-Null Count  Dtype
---   ------                    --------------  -----
 0    FIGHT_LINK                8447 non-null   object
 1    R_FIGHTER                 8447 non-null   object
 2    R_FIGHTER_ID              8447 non-null   object
 3    R_FIGHTER_LINK            8447 non-null   object
 4    R_FIGHTER_RESULT          8447 non-null   object
 5    B_FIGHTER                 8447 non-null   object
 6    B_FIGHTER_ID              8447 non-null   object
 7    B_FIGHTER_LINK            8447 non-null   object
 8    B_FIGHTER_RESULT          8447 non-null   object
 9    METHOD                    8447 non-null   object
 10   ROUND                     8447 non-null   int64
 11   TIME                      8447 non-null   int64
 12   TIME FORMAT               8447 non-null   object
 13   REFEREE                   8447 non-null   object
 14   DETAILS                   8447 non-null   object
 15   WEIGHT_CLASS              8447 non-null   object
 16   TITLE_FIGHT               8447 non-null   bool
 17   PERF_BONUS                8447 non-null   bool
 18   R_KD_TOT                  8447 non-null   int64
 19   B_KD_TOT                  8447 non-null   int64
 20   R_TD_PCT_TOT              8447 non-null   float64
 21   B_TD_PCT_TOT              8447 non-null   float64
 22   R_SUB_ATT_TOT             8447 non-null   int64
 23   B_SUB_ATT_TOT             8447 non-null   int64
 24   R_REV_TOT                 8447 non-null   int64
 25   B_REV_TOT                 8447 non-null   int64
 26   R_CTRL_TOT                8447 non-null   int64
 27   B_CTRL_TOT                8447 non-null   int64
 28   R_KD_R1                   8447 non-null   int64
 29   B_KD_R1                   8447 non-null   int64
 30   R_TD_PCT_R1               8447 non-null   float64
 31   B_TD_PCT_R1               8447 non-null   float64
 32   R_SUB_ATT_R1              8447 non-null   int64
 33   B_SUB_ATT_R1              8447 non-null   int64
 34   R_REV_R1                  8447 non-null   int64
 35   B_REV_R1                  8447 non-null   int64
 36   R_CTRL_R1                 8447 non-null   int64
 37   B_CTRL_R1                 8447 non-null   int64
 38   R_KD_R2                   8447 non-null   int64
 39   B_KD_R2                   8447 non-null   int64
 40   R_TD_PCT_R2               8447 non-null   float64
 41   B_TD_PCT_R2               8447 non-null   float64
 42   R_SUB_ATT_R2              8447 non-null   int64
 43   B_SUB_ATT_R2              8447 non-null   int64
 44   R_REV_R2                  8447 non-null   int64
 45   B_REV_R2                  8447 non-null   int64
 46   R_CTRL_R2                 8447 non-null   int64
 47   B_CTRL_R2                 8447 non-null   int64
 48   R_SIG_STR_PCT_TOT         8447 non-null   float64
 49   B_SIG_STR_PCT_TOT         8447 non-null   float64
 50   R_SIG_STR_PCT_R1          8447 non-null   float64
 51   B_SIG_STR_PCT_R1          8447 non-null   float64
 52   R_SIG_STR_PCT_R2          8447 non-null   float64
 53   B_SIG_STR_PCT_R2          8447 non-null   float64
 54   R_KD_R3                   8447 non-null   int64
 55   B_KD_R3                   8447 non-null   int64
 56   R_TD_PCT_R3               8447 non-null   float64
 57   B_TD_PCT_R3               8447 non-null   float64
 58   R_SUB_ATT_R3              8447 non-null   int64
 59   B_SUB_ATT_R3              8447 non-null   int64
 60   R_REV_R3                  8447 non-null   int64
 61   B_REV_R3                  8447 non-null   int64
 62   R_CTRL_R3                 8447 non-null   int64
 63   B_CTRL_R3                 8447 non-null   int64
 64   R_SIG_STR_PCT_R3          8447 non-null   float64
 65   B_SIG_STR_PCT_R3          8447 non-null   float64
 66   EVENT_ID                  8447 non-null   object
 67   DATE                      8447 non-null   datetime64[ns]
 68   R_KD_R4                   8447 non-null   int64
 69   B_KD_R4                   8447 non-null   int64
 70   R_TD_PCT_R4               8447 non-null   float64
 71   B_TD_PCT_R4               8447 non-null   float64
 72   R_SUB_ATT_R4              8447 non-null   int64
 73   B_SUB_ATT_R4              8447 non-null   int64
 74   R_REV_R4                  8447 non-null   int64
 75   B_REV_R4                  8447 non-null   int64
 76   R_CTRL_R4                 8447 non-null   int64
 77   B_CTRL_R4                 8447 non-null   int64
 78   R_KD_R5                   8447 non-null   int64
 79   B_KD_R5                   8447 non-null   int64
 80   R_TD_PCT_R5               8447 non-null   float64
 81   B_TD_PCT_R5               8447 non-null   float64
 82   R_SUB_ATT_R5              8447 non-null   int64
 83   B_SUB_ATT_R5              8447 non-null   int64
 84   R_REV_R5                  8447 non-null   int64
 85   B_REV_R5                  8447 non-null   int64
 86   R_CTRL_R5                 8447 non-null   int64
 87   B_CTRL_R5                 8447 non-null   int64
 88   R_SIG_STR_PCT_R4          8447 non-null   float64
 89   B_SIG_STR_PCT_R4          8447 non-null   float64
 90   R_SIG_STR_PCT_R5          8447 non-null   float64
 91   B_SIG_STR_PCT_R5          8447 non-null   float64
 92   R_ALL_STR_TOT_LANDED      8447 non-null   int64
 93   R_ALL_STR_TOT_ATTEMPTED   8447 non-null   int64
 94   B_ALL_STR_TOT_LANDED      8447 non-null   int64
 95   B_ALL_STR_TOT_ATTEMPTED   8447 non-null   int64
 96   R_TD_TOT_LANDED           8447 non-null   int64
 97   R_TD_TOT_ATTEMPTED        8447 non-null   int64
 98   B_TD_TOT_LANDED           8447 non-null   int64
 99   B_TD_TOT_ATTEMPTED        8447 non-null   int64
 100  R_ALL_STR_R1_LANDED       8447 non-null   int64
 101  R_ALL_STR_R1_ATTEMPTED    8447 non-null   int64
 102  B_ALL_STR_R1_LANDED       8447 non-null   int64
 103  B_ALL_STR_R1_ATTEMPTED    8447 non-null   int64
 104  R_TD_R1_LANDED            8447 non-null   int64
 105  R_TD_R1_ATTEMPTED         8447 non-null   int64
 106  B_TD_R1_LANDED            8447 non-null   int64
 107  B_TD_R1_ATTEMPTED         8447 non-null   int64
 108  R_ALL_STR_R2_LANDED       8447 non-null   int64
 109  R_ALL_STR_R2_ATTEMPTED    8447 non-null   int64
 110  B_ALL_STR_R2_LANDED       8447 non-null   int64
 111  B_ALL_STR_R2_ATTEMPTED    8447 non-null   int64
 112  R_TD_R2_LANDED            8447 non-null   int64
 113  R_TD_R2_ATTEMPTED         8447 non-null   int64
 114  B_TD_R2_LANDED            8447 non-null   int64
 115  B_TD_R2_ATTEMPTED         8447 non-null   int64
 116  R_SIG_STR_TOT_LANDED      8447 non-null   int64
 117  R_SIG_STR_TOT_ATTEMPTED   8447 non-null   int64
 118  B_SIG_STR_TOT_LANDED      8447 non-null   int64
 119  B_SIG_STR_TOT_ATTEMPTED   8447 non-null   int64
 120  R_HEAD_TOT_LANDED         8447 non-null   int64
 121  R_HEAD_TOT_ATTEMPTED      8447 non-null   int64
 122  B_HEAD_TOT_LANDED         8447 non-null   int64
 123  B_HEAD_TOT_ATTEMPTED      8447 non-null   int64
 124  R_BODY_TOT_LANDED         8447 non-null   int64
 125  R_BODY_TOT_ATTEMPTED      8447 non-null   int64
 126  B_BODY_TOT_LANDED         8447 non-null   int64
 127  B_BODY_TOT_ATTEMPTED      8447 non-null   int64
 128  R_LEG_TOT_LANDED          8447 non-null   int64
 129  R_LEG_TOT_ATTEMPTED       8447 non-null   int64
 130  B_LEG_TOT_LANDED          8447 non-null   int64
 131  B_LEG_TOT_ATTEMPTED       8447 non-null   int64
 132  R_DISTANCE_TOT_LANDED     8447 non-null   int64
 133  R_DISTANCE_TOT_ATTEMPTED  8447 non-null   int64
 134  B_DISTANCE_TOT_LANDED     8447 non-null   int64
 135  B_DISTANCE_TOT_ATTEMPTED  8447 non-null   int64
 136  R_CLINCH_TOT_LANDED       8447 non-null   int64
 137  R_CLINCH_TOT_ATTEMPTED    8447 non-null   int64
 138  B_CLINCH_TOT_LANDED       8447 non-null   int64
 139  B_CLINCH_TOT_ATTEMPTED    8447 non-null   int64
 140  R_GROUND_TOT_LANDED       8447 non-null   int64
 141  R_GROUND_TOT_ATTEMPTED    8447 non-null   int64
 142  B_GROUND_TOT_LANDED       8447 non-null   int64
 143  B_GROUND_TOT_ATTEMPTED    8447 non-null   int64
 144  R_SIG_STR_R1_LANDED       8447 non-null   int64
 145  R_SIG_STR_R1_ATTEMPTED    8447 non-null   int64
 146  B_SIG_STR_R1_LANDED       8447 non-null   int64
 147  B_SIG_STR_R1_ATTEMPTED    8447 non-null   int64
 148  R_HEAD_R1_LANDED          8447 non-null   int64
 149  R_HEAD_R1_ATTEMPTED       8447 non-null   int64
 150  B_HEAD_R1_LANDED          8447 non-null   int64
 151  B_HEAD_R1_ATTEMPTED       8447 non-null   int64
 152  R_BODY_R1_LANDED          8447 non-null   int64
 153  R_BODY_R1_ATTEMPTED       8447 non-null   int64
 154  B_BODY_R1_LANDED          8447 non-null   int64
 155  B_BODY_R1_ATTEMPTED       8447 non-null   int64
 156  R_LEG_R1_LANDED           8447 non-null   int64
 157  R_LEG_R1_ATTEMPTED        8447 non-null   int64
 158  B_LEG_R1_LANDED           8447 non-null   int64
 159  B_LEG_R1_ATTEMPTED        8447 non-null   int64
 160  R_DISTANCE_R1_LANDED      8447 non-null   int64
 161  R_DISTANCE_R1_ATTEMPTED   8447 non-null   int64
 162  B_DISTANCE_R1_LANDED      8447 non-null   int64
 163  B_DISTANCE_R1_ATTEMPTED   8447 non-null   int64
 164  R_CLINCH_R1_LANDED        8447 non-null   int64
 165  R_CLINCH_R1_ATTEMPTED     8447 non-null   int64
 166  B_CLINCH_R1_LANDED        8447 non-null   int64
 167  B_CLINCH_R1_ATTEMPTED     8447 non-null   int64
 168  R_GROUND_R1_LANDED        8447 non-null   int64
 169  R_GROUND_R1_ATTEMPTED     8447 non-null   int64
 170  B_GROUND_R1_LANDED        8447 non-null   int64
 171  B_GROUND_R1_ATTEMPTED     8447 non-null   int64
 172  R_SIG_STR_R2_LANDED       8447 non-null   int64
 173  R_SIG_STR_R2_ATTEMPTED    8447 non-null   int64
 174  B_SIG_STR_R2_LANDED       8447 non-null   int64
 175  B_SIG_STR_R2_ATTEMPTED    8447 non-null   int64
 176  R_HEAD_R2_LANDED          8447 non-null   int64
 177  R_HEAD_R2_ATTEMPTED       8447 non-null   int64
 178  B_HEAD_R2_LANDED          8447 non-null   int64
 179  B_HEAD_R2_ATTEMPTED       8447 non-null   int64
 180  R_BODY_R2_LANDED          8447 non-null   int64
 181  R_BODY_R2_ATTEMPTED       8447 non-null   int64
 182  B_BODY_R2_LANDED          8447 non-null   int64
 183  B_BODY_R2_ATTEMPTED       8447 non-null   int64
 184  R_LEG_R2_LANDED           8447 non-null   int64
 185  R_LEG_R2_ATTEMPTED        8447 non-null   int64
 186  B_LEG_R2_LANDED           8447 non-null   int64
 187  B_LEG_R2_ATTEMPTED        8447 non-null   int64
 188  R_DISTANCE_R2_LANDED      8447 non-null   int64
 189  R_DISTANCE_R2_ATTEMPTED   8447 non-null   int64
 190  B_DISTANCE_R2_LANDED      8447 non-null   int64
 191  B_DISTANCE_R2_ATTEMPTED   8447 non-null   int64
 192  R_CLINCH_R2_LANDED        8447 non-null   int64
 193  R_CLINCH_R2_ATTEMPTED     8447 non-null   int64
 194  B_CLINCH_R2_LANDED        8447 non-null   int64
 195  B_CLINCH_R2_ATTEMPTED     8447 non-null   int64
 196  R_GROUND_R2_LANDED        8447 non-null   int64
 197  R_GROUND_R2_ATTEMPTED     8447 non-null   int64
 198  B_GROUND_R2_LANDED        8447 non-null   int64
 199  B_GROUND_R2_ATTEMPTED     8447 non-null   int64
 200  R_ALL_STR_R3_LANDED       8447 non-null   int64
 201  R_ALL_STR_R3_ATTEMPTED    8447 non-null   int64
 202  B_ALL_STR_R3_LANDED       8447 non-null   int64
 203  B_ALL_STR_R3_ATTEMPTED    8447 non-null   int64
 204  R_TD_R3_LANDED            8447 non-null   int64
 205  R_TD_R3_ATTEMPTED         8447 non-null   int64
 206  B_TD_R3_LANDED            8447 non-null   int64
 207  B_TD_R3_ATTEMPTED         8447 non-null   int64
 208  R_SIG_STR_R3_LANDED       8447 non-null   int64
 209  R_SIG_STR_R3_ATTEMPTED    8447 non-null   int64
 210  B_SIG_STR_R3_LANDED       8447 non-null   int64
 211  B_SIG_STR_R3_ATTEMPTED    8447 non-null   int64
 212  R_HEAD_R3_LANDED          8447 non-null   int64
 213  R_HEAD_R3_ATTEMPTED       8447 non-null   int64
 214  B_HEAD_R3_LANDED          8447 non-null   int64
 215  B_HEAD_R3_ATTEMPTED       8447 non-null   int64
 216  R_BODY_R3_LANDED          8447 non-null   int64
 217  R_BODY_R3_ATTEMPTED       8447 non-null   int64
 218  B_BODY_R3_LANDED          8447 non-null   int64
 219  B_BODY_R3_ATTEMPTED       8447 non-null   int64
 220  R_LEG_R3_LANDED           8447 non-null   int64
 221  R_LEG_R3_ATTEMPTED        8447 non-null   int64
 222  B_LEG_R3_LANDED           8447 non-null   int64
 223  B_LEG_R3_ATTEMPTED        8447 non-null   int64
 224  R_DISTANCE_R3_LANDED      8447 non-null   int64
 225  R_DISTANCE_R3_ATTEMPTED   8447 non-null   int64
 226  B_DISTANCE_R3_LANDED      8447 non-null   int64
 227  B_DISTANCE_R3_ATTEMPTED   8447 non-null   int64
 228  R_CLINCH_R3_LANDED        8447 non-null   int64
 229  R_CLINCH_R3_ATTEMPTED     8447 non-null   int64
 230  B_CLINCH_R3_LANDED        8447 non-null   int64
 231  B_CLINCH_R3_ATTEMPTED     8447 non-null   int64
 232  R_GROUND_R3_LANDED        8447 non-null   int64
 233  R_GROUND_R3_ATTEMPTED     8447 non-null   int64
 234  B_GROUND_R3_LANDED        8447 non-null   int64
 235  B_GROUND_R3_ATTEMPTED     8447 non-null   int64
 236  R_ALL_STR_R4_LANDED       8447 non-null   int64
 237  R_ALL_STR_R4_ATTEMPTED    8447 non-null   int64
 238  B_ALL_STR_R4_LANDED       8447 non-null   int64
 239  B_ALL_STR_R4_ATTEMPTED    8447 non-null   int64
 240  R_TD_R4_LANDED            8447 non-null   int64
 241  R_TD_R4_ATTEMPTED         8447 non-null   int64
 242  B_TD_R4_LANDED            8447 non-null   int64
 243  B_TD_R4_ATTEMPTED         8447 non-null   int64
 244  R_ALL_STR_R5_LANDED       8447 non-null   int64
 245  R_ALL_STR_R5_ATTEMPTED    8447 non-null   int64
 246  B_ALL_STR_R5_LANDED       8447 non-null   int64
 247  B_ALL_STR_R5_ATTEMPTED    8447 non-null   int64
 248  R_TD_R5_LANDED            8447 non-null   int64
 249  R_TD_R5_ATTEMPTED         8447 non-null   int64
 250  B_TD_R5_LANDED            8447 non-null   int64
 251  B_TD_R5_ATTEMPTED         8447 non-null   int64
 252  R_SIG_STR_R4_LANDED       8447 non-null   int64
 253  R_SIG_STR_R4_ATTEMPTED    8447 non-null   int64
 254  B_SIG_STR_R4_LANDED       8447 non-null   int64
 255  B_SIG_STR_R4_ATTEMPTED    8447 non-null   int64
 256  R_HEAD_R4_LANDED          8447 non-null   int64
 257  R_HEAD_R4_ATTEMPTED       8447 non-null   int64
 258  B_HEAD_R4_LANDED          8447 non-null   int64
 259  B_HEAD_R4_ATTEMPTED       8447 non-null   int64
 260  R_BODY_R4_LANDED          8447 non-null   int64
 261  R_BODY_R4_ATTEMPTED       8447 non-null   int64
 262  B_BODY_R4_LANDED          8447 non-null   int64
 263  B_BODY_R4_ATTEMPTED       8447 non-null   int64
 264  R_LEG_R4_LANDED           8447 non-null   int64
 265  R_LEG_R4_ATTEMPTED        8447 non-null   int64
 266  B_LEG_R4_LANDED           8447 non-null   int64
 267  B_LEG_R4_ATTEMPTED        8447 non-null   int64
 268  R_DISTANCE_R4_LANDED      8447 non-null   int64
 269  R_DISTANCE_R4_ATTEMPTED   8447 non-null   int64
 270  B_DISTANCE_R4_LANDED      8447 non-null   int64
 271  B_DISTANCE_R4_ATTEMPTED   8447 non-null   int64
 272  R_CLINCH_R4_LANDED        8447 non-null   int64
 273  R_CLINCH_R4_ATTEMPTED     8447 non-null   int64
 274  B_CLINCH_R4_LANDED        8447 non-null   int64
 275  B_CLINCH_R4_ATTEMPTED     8447 non-null   int64
 276  R_GROUND_R4_LANDED        8447 non-null   int64
 277  R_GROUND_R4_ATTEMPTED     8447 non-null   int64
 278  B_GROUND_R4_LANDED        8447 non-null   int64
 279  B_GROUND_R4_ATTEMPTED     8447 non-null   int64
 280  R_SIG_STR_R5_LANDED       8447 non-null   int64
 281  R_SIG_STR_R5_ATTEMPTED    8447 non-null   int64
 282  B_SIG_STR_R5_LANDED       8447 non-null   int64
 283  B_SIG_STR_R5_ATTEMPTED    8447 non-null   int64
 284  R_HEAD_R5_LANDED          8447 non-null   int64
 285  R_HEAD_R5_ATTEMPTED       8447 non-null   int64
 286  B_HEAD_R5_LANDED          8447 non-null   int64
 287  B_HEAD_R5_ATTEMPTED       8447 non-null   int64
 288  R_BODY_R5_LANDED          8447 non-null   int64
 289  R_BODY_R5_ATTEMPTED       8447 non-null   int64
 290  B_BODY_R5_LANDED          8447 non-null   int64
 291  B_BODY_R5_ATTEMPTED       8447 non-null   int64
 292  R_LEG_R5_LANDED           8447 non-null   int64
 293  R_LEG_R5_ATTEMPTED        8447 non-null   int64
 294  B_LEG_R5_LANDED           8447 non-null   int64
 295  B_LEG_R5_ATTEMPTED        8447 non-null   int64
 296  R_DISTANCE_R5_LANDED      8447 non-null   int64
 297  R_DISTANCE_R5_ATTEMPTED   8447 non-null   int64
 298  B_DISTANCE_R5_LANDED      8447 non-null   int64
 299  B_DISTANCE_R5_ATTEMPTED   8447 non-null   int64
 300  R_CLINCH_R5_LANDED        8447 non-null   int64
 301  R_CLINCH_R5_ATTEMPTED     8447 non-null   int64
 302  B_CLINCH_R5_LANDED        8447 non-null   int64
 303  B_CLINCH_R5_ATTEMPTED     8447 non-null   int64
 304  R_GROUND_R5_LANDED        8447 non-null   int64
 305  R_GROUND_R5_ATTEMPTED     8447 non-null   int64
 306  B_GROUND_R5_LANDED        8447 non-null   int64
 307  B_GROUND_R5_ATTEMPTED     8447 non-null   int64
dtypes: bool(2), datetime64[ns](1), float64(24), int64(266), object(15)
memory usage: 20.1+ MB

In [5]:
td_df

,R_TD_PCT_TOT,B_TD_PCT_TOT,R_TD_PCT_R1,B_TD_PCT_R1,R_TD_PCT_R2,B_TD_PCT_R2,R_TD_PCT_R3,B_TD_PCT_R3,R_TD_PCT_R4,B_TD_PCT_R4,...,B_TD_R3_LANDED,B_TD_R3_ATTEMPTED,R_TD_R4_LANDED,R_TD_R4_ATTEMPTED,B_TD_R4_LANDED,B_TD_R4_ATTEMPTED,R_TD_R5_LANDED,R_TD_R5_ATTEMPTED,B_TD_R5_LANDED,B_TD_R5_ATTEMPTED
FIGHT_ID,,,,,,,,,,,,,,,,,,,,,
5f5b626e67529056,0.5,-1.0,0.33,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
b2218930b982d9b6,0.0,0.0,0.00,-1.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0,1,-1,-1,-1,-1,-1,-1,-1,-1
870d374f8d9af65a,-1.0,-1.0,-1.00,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
8ed609d80e135d94,-1.0,-1.0,-1.00,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
e8307c7686c42d8c,-1.0,-1.0,-1.00,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3b020d4914b44fc8,-1.0,1.0,-1.00,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
d917c8c7461b9831,1.0,0.0,1.00,0.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
ccee020be2e8d9f6,1.0,-1.0,1.00,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4b9ae533ccb3fcdf,0.0,-1.0,0.00,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4acab67848e78327,1.0,-1.0,1.00,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [8]:
list(td_df.loc["5f5b626e67529056"])

[0.5,
 -1.0,
 0.33,
 -1.0,
 1.0,
 -1.0,
 -1.0,
 -1.0,
 -1.0,
 -1.0,
 -1.0,
 -1.0,
 2.0,
 4.0,
 0.0,
 0.0,
 1.0,
 3.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 -1.0,
 -1.0,
 -1.0,
 -1.0,
 -1.0,
 -1.0,
 -1.0,
 -1.0,
 -1.0,
 -1.0,
 -1.0,
 -1.0]

In [8]:
processed_fight_data.info(show_counts = True, verbose=True)

<class 'pandas.core.frame.DataFrame'>
Index: 8447 entries, 5f5b626e67529056 to 4acab67848e78327
Data columns (total 296 columns):
 #    Column                    Non-Null Count  Dtype
---   ------                    --------------  -----
 0    FIGHT_LINK                8447 non-null   object
 1    R_FIGHTER                 8447 non-null   object
 2    R_FIGHTER_ID              8447 non-null   object
 3    R_FIGHTER_LINK            8447 non-null   object
 4    R_FIGHTER_RESULT          8447 non-null   object
 5    B_FIGHTER                 8447 non-null   object
 6    B_FIGHTER_ID              8447 non-null   object
 7    B_FIGHTER_LINK            8447 non-null   object
 8    B_FIGHTER_RESULT          8447 non-null   object
 9    METHOD                    8447 non-null   object
 10   ROUND                     8447 non-null   int64
 11   TIME                      8447 non-null   int64
 12   TIME FORMAT               8447 non-null   object
 13   REFEREE                   8447 non-null   object
 14   DETAILS                   8447 non-null   object
 15   WEIGHT_CLASS              8447 non-null   object
 16   TITLE_FIGHT               8447 non-null   bool
 17   PERF_BONUS                8447 non-null   bool
 18   R_KD_TOT                  8447 non-null   int64
 19   B_KD_TOT                  8447 non-null   int64
 20   R_TD_TOT                  8447 non-null   object
 21   B_TD_TOT                  8447 non-null   object
 22   R_TD_PCT_TOT              8447 non-null   float64
 23   B_TD_PCT_TOT              8447 non-null   float64
 24   R_SUB_ATT_TOT             8447 non-null   int64
 25   B_SUB_ATT_TOT             8447 non-null   int64
 26   R_REV_TOT                 8447 non-null   int64
 27   B_REV_TOT                 8447 non-null   int64
 28   R_CTRL_TOT                8447 non-null   object
 29   B_CTRL_TOT                8447 non-null   object
 30   R_KD_R1                   8447 non-null   int64
 31   B_KD_R1                   8447 non-null   int64
 32   R_TD_R1                   8447 non-null   object
 33   B_TD_R1                   8447 non-null   object
 34   R_TD_PCT_R1               8447 non-null   float64
 35   B_TD_PCT_R1               8447 non-null   float64
 36   R_SUB_ATT_R1              8447 non-null   int64
 37   B_SUB_ATT_R1              8447 non-null   int64
 38   R_REV_R1                  8447 non-null   int64
 39   B_REV_R1                  8447 non-null   int64
 40   R_CTRL_R1                 8447 non-null   object
 41   B_CTRL_R1                 8447 non-null   object
 42   R_KD_R2                   6077 non-null   float64
 43   B_KD_R2                   6077 non-null   float64
 44   R_TD_R2                   8447 non-null   object
 45   B_TD_R2                   8447 non-null   object
 46   R_TD_PCT_R2               8447 non-null   float64
 47   B_TD_PCT_R2               8447 non-null   float64
 48   R_SUB_ATT_R2              6077 non-null   float64
 49   B_SUB_ATT_R2              6077 non-null   float64
 50   R_REV_R2                  6077 non-null   float64
 51   B_REV_R2                  6077 non-null   float64
 52   R_CTRL_R2                 8447 non-null   object
 53   B_CTRL_R2                 8447 non-null   object
 54   R_SIG_STR_PCT_TOT         8447 non-null   float64
 55   B_SIG_STR_PCT_TOT         8447 non-null   float64
 56   R_SIG_STR_PCT_R1          8447 non-null   float64
 57   B_SIG_STR_PCT_R1          8447 non-null   float64
 58   R_SIG_STR_PCT_R2          8447 non-null   float64
 59   B_SIG_STR_PCT_R2          8447 non-null   float64
 60   R_KD_R3                   4679 non-null   float64
 61   B_KD_R3                   4679 non-null   float64
 62   R_TD_R3                   8447 non-null   object
 63   B_TD_R3                   8447 non-null   object
 64   R_TD_PCT_R3               8447 non-null   float64
 65   B_TD_PCT_R3               8447 non-null   float64
 66   R_SUB_ATT_R3              4679 non-null   float64
 67   B_SUB_ATT_R3              4679 non-null   float64
 68   R_REV_R3                  4679 non-null   float64
 69   B_REV_R3                  4679 non-null   float64
 70   R_CTRL_R3                 8447 non-null   object
 71   B_CTRL_R3                 8447 non-null   object
 72   R_SIG_STR_PCT_R3          8447 non-null   float64
 73   B_SIG_STR_PCT_R3          8447 non-null   float64
 74   EVENT_ID                  8447 non-null   object
 75   DATE                      8447 non-null   datetime64[ns]
 76   R_KD_R4                   376 non-null    float64
 77   B_KD_R4                   376 non-null    float64
 78   R_TD_R4                   8447 non-null   object
 79   B_TD_R4                   8447 non-null   object
 80   R_TD_PCT_R4               8447 non-null   float64
 81   B_TD_PCT_R4               8447 non-null   float64
 82   R_SUB_ATT_R4              376 non-null    float64
 83   B_SUB_ATT_R4              376 non-null    float64
 84   R_REV_R4                  376 non-null    float64
 85   B_REV_R4                  376 non-null    float64
 86   R_CTRL_R4                 8447 non-null   object
 87   B_CTRL_R4                 8447 non-null   object
 88   R_KD_R5                   326 non-null    float64
 89   B_KD_R5                   326 non-null    float64
 90   R_TD_R5                   8447 non-null   object
 91   B_TD_R5                   8447 non-null   object
 92   R_TD_PCT_R5               8447 non-null   float64
 93   B_TD_PCT_R5               8447 non-null   float64
 94   R_SUB_ATT_R5              326 non-null    float64
 95   B_SUB_ATT_R5              326 non-null    float64
 96   R_REV_R5                  326 non-null    float64
 97   B_REV_R5                  326 non-null    float64
 98   R_CTRL_R5                 8447 non-null   object
 99   B_CTRL_R5                 8447 non-null   object
 100  R_SIG_STR_PCT_R4          8447 non-null   float64
 101  B_SIG_STR_PCT_R4          8447 non-null   float64
 102  R_SIG_STR_PCT_R5          8447 non-null   float64
 103  B_SIG_STR_PCT_R5          8447 non-null   float64
 104  R_ALL_STR_TOT_LANDED      8447 non-null   int64
 105  R_ALL_STR_TOT_ATTEMPTED   8447 non-null   int64
 106  B_ALL_STR_TOT_LANDED      8447 non-null   int64
 107  B_ALL_STR_TOT_ATTEMPTED   8447 non-null   int64
 108  R_ALL_STR_R1_LANDED       8447 non-null   int64
 109  R_ALL_STR_R1_ATTEMPTED    8447 non-null   int64
 110  B_ALL_STR_R1_LANDED       8447 non-null   int64
 111  B_ALL_STR_R1_ATTEMPTED    8447 non-null   int64
 112  R_ALL_STR_R2_LANDED       8447 non-null   int64
 113  R_ALL_STR_R2_ATTEMPTED    8447 non-null   int64
 114  B_ALL_STR_R2_LANDED       8447 non-null   int64
 115  B_ALL_STR_R2_ATTEMPTED    8447 non-null   int64
 116  R_SIG_STR_TOT_LANDED      8447 non-null   int64
 117  R_SIG_STR_TOT_ATTEMPTED   8447 non-null   int64
 118  B_SIG_STR_TOT_LANDED      8447 non-null   int64
 119  B_SIG_STR_TOT_ATTEMPTED   8447 non-null   int64
 120  R_HEAD_TOT_LANDED         8447 non-null   int64
 121  R_HEAD_TOT_ATTEMPTED      8447 non-null   int64
 122  B_HEAD_TOT_LANDED         8447 non-null   int64
 123  B_HEAD_TOT_ATTEMPTED      8447 non-null   int64
 124  R_BODY_TOT_LANDED         8447 non-null   int64
 125  R_BODY_TOT_ATTEMPTED      8447 non-null   int64
 126  B_BODY_TOT_LANDED         8447 non-null   int64
 127  B_BODY_TOT_ATTEMPTED      8447 non-null   int64
 128  R_LEG_TOT_LANDED          8447 non-null   int64
 129  R_LEG_TOT_ATTEMPTED       8447 non-null   int64
 130  B_LEG_TOT_LANDED          8447 non-null   int64
 131  B_LEG_TOT_ATTEMPTED       8447 non-null   int64
 132  R_DISTANCE_TOT_LANDED     8447 non-null   int64
 133  R_DISTANCE_TOT_ATTEMPTED  8447 non-null   int64
 134  B_DISTANCE_TOT_LANDED     8447 non-null   int64
 135  B_DISTANCE_TOT_ATTEMPTED  8447 non-null   int64
 136  R_CLINCH_TOT_LANDED       8447 non-null   int64
 137  R_CLINCH_TOT_ATTEMPTED    8447 non-null   int64
 138  B_CLINCH_TOT_LANDED       8447 non-null   int64
 139  B_CLINCH_TOT_ATTEMPTED    8447 non-null   int64
 140  R_GROUND_TOT_LANDED       8447 non-null   int64
 141  R_GROUND_TOT_ATTEMPTED    8447 non-null   int64
 142  B_GROUND_TOT_LANDED       8447 non-null   int64
 143  B_GROUND_TOT_ATTEMPTED    8447 non-null   int64
 144  R_SIG_STR_R1_LANDED       8447 non-null   int64
 145  R_SIG_STR_R1_ATTEMPTED    8447 non-null   int64
 146  B_SIG_STR_R1_LANDED       8447 non-null   int64
 147  B_SIG_STR_R1_ATTEMPTED    8447 non-null   int64
 148  R_HEAD_R1_LANDED          8447 non-null   int64
 149  R_HEAD_R1_ATTEMPTED       8447 non-null   int64
 150  B_HEAD_R1_LANDED          8447 non-null   int64
 151  B_HEAD_R1_ATTEMPTED       8447 non-null   int64
 152  R_BODY_R1_LANDED          8447 non-null   int64
 153  R_BODY_R1_ATTEMPTED       8447 non-null   int64
 154  B_BODY_R1_LANDED          8447 non-null   int64
 155  B_BODY_R1_ATTEMPTED       8447 non-null   int64
 156  R_LEG_R1_LANDED           8447 non-null   int64
 157  R_LEG_R1_ATTEMPTED        8447 non-null   int64
 158  B_LEG_R1_LANDED           8447 non-null   int64
 159  B_LEG_R1_ATTEMPTED        8447 non-null   int64
 160  R_DISTANCE_R1_LANDED      8447 non-null   int64
 161  R_DISTANCE_R1_ATTEMPTED   8447 non-null   int64
 162  B_DISTANCE_R1_LANDED      8447 non-null   int64
 163  B_DISTANCE_R1_ATTEMPTED   8447 non-null   int64
 164  R_CLINCH_R1_LANDED        8447 non-null   int64
 165  R_CLINCH_R1_ATTEMPTED     8447 non-null   int64
 166  B_CLINCH_R1_LANDED        8447 non-null   int64
 167  B_CLINCH_R1_ATTEMPTED     8447 non-null   int64
 168  R_GROUND_R1_LANDED        8447 non-null   int64
 169  R_GROUND_R1_ATTEMPTED     8447 non-null   int64
 170  B_GROUND_R1_LANDED        8447 non-null   int64
 171  B_GROUND_R1_ATTEMPTED     8447 non-null   int64
 172  R_SIG_STR_R2_LANDED       8447 non-null   int64
 173  R_SIG_STR_R2_ATTEMPTED    8447 non-null   int64
 174  B_SIG_STR_R2_LANDED       8447 non-null   int64
 175  B_SIG_STR_R2_ATTEMPTED    8447 non-null   int64
 176  R_HEAD_R2_LANDED          8447 non-null   int64
 177  R_HEAD_R2_ATTEMPTED       8447 non-null   int64
 178  B_HEAD_R2_LANDED          8447 non-null   int64
 179  B_HEAD_R2_ATTEMPTED       8447 non-null   int64
 180  R_BODY_R2_LANDED          8447 non-null   int64
 181  R_BODY_R2_ATTEMPTED       8447 non-null   int64
 182  B_BODY_R2_LANDED          8447 non-null   int64
 183  B_BODY_R2_ATTEMPTED       8447 non-null   int64
 184  R_LEG_R2_LANDED           8447 non-null   int64
 185  R_LEG_R2_ATTEMPTED        8447 non-null   int64
 186  B_LEG_R2_LANDED           8447 non-null   int64
 187  B_LEG_R2_ATTEMPTED        8447 non-null   int64
 188  R_DISTANCE_R2_LANDED      8447 non-null   int64
 189  R_DISTANCE_R2_ATTEMPTED   8447 non-null   int64
 190  B_DISTANCE_R2_LANDED      8447 non-null   int64
 191  B_DISTANCE_R2_ATTEMPTED   8447 non-null   int64
 192  R_CLINCH_R2_LANDED        8447 non-null   int64
 193  R_CLINCH_R2_ATTEMPTED     8447 non-null   int64
 194  B_CLINCH_R2_LANDED        8447 non-null   int64
 195  B_CLINCH_R2_ATTEMPTED     8447 non-null   int64
 196  R_GROUND_R2_LANDED        8447 non-null   int64
 197  R_GROUND_R2_ATTEMPTED     8447 non-null   int64
 198  B_GROUND_R2_LANDED        8447 non-null   int64
 199  B_GROUND_R2_ATTEMPTED     8447 non-null   int64
 200  R_ALL_STR_R3_LANDED       8447 non-null   int64
 201  R_ALL_STR_R3_ATTEMPTED    8447 non-null   int64
 202  B_ALL_STR_R3_LANDED       8447 non-null   int64
 203  B_ALL_STR_R3_ATTEMPTED    8447 non-null   int64
 204  R_SIG_STR_R3_LANDED       8447 non-null   int64
 205  R_SIG_STR_R3_ATTEMPTED    8447 non-null   int64
 206  B_SIG_STR_R3_LANDED       8447 non-null   int64
 207  B_SIG_STR_R3_ATTEMPTED    8447 non-null   int64
 208  R_HEAD_R3_LANDED          8447 non-null   int64
 209  R_HEAD_R3_ATTEMPTED       8447 non-null   int64
 210  B_HEAD_R3_LANDED          8447 non-null   int64
 211  B_HEAD_R3_ATTEMPTED       8447 non-null   int64
 212  R_BODY_R3_LANDED          8447 non-null   int64
 213  R_BODY_R3_ATTEMPTED       8447 non-null   int64
 214  B_BODY_R3_LANDED          8447 non-null   int64
 215  B_BODY_R3_ATTEMPTED       8447 non-null   int64
 216  R_LEG_R3_LANDED           8447 non-null   int64
 217  R_LEG_R3_ATTEMPTED        8447 non-null   int64
 218  B_LEG_R3_LANDED           8447 non-null   int64
 219  B_LEG_R3_ATTEMPTED        8447 non-null   int64
 220  R_DISTANCE_R3_LANDED      8447 non-null   int64
 221  R_DISTANCE_R3_ATTEMPTED   8447 non-null   int64
 222  B_DISTANCE_R3_LANDED      8447 non-null   int64
 223  B_DISTANCE_R3_ATTEMPTED   8447 non-null   int64
 224  R_CLINCH_R3_LANDED        8447 non-null   int64
 225  R_CLINCH_R3_ATTEMPTED     8447 non-null   int64
 226  B_CLINCH_R3_LANDED        8447 non-null   int64
 227  B_CLINCH_R3_ATTEMPTED     8447 non-null   int64
 228  R_GROUND_R3_LANDED        8447 non-null   int64
 229  R_GROUND_R3_ATTEMPTED     8447 non-null   int64
 230  B_GROUND_R3_LANDED        8447 non-null   int64
 231  B_GROUND_R3_ATTEMPTED     8447 non-null   int64
 232  R_ALL_STR_R4_LANDED       8447 non-null   int64
 233  R_ALL_STR_R4_ATTEMPTED    8447 non-null   int64
 234  B_ALL_STR_R4_LANDED       8447 non-null   int64
 235  B_ALL_STR_R4_ATTEMPTED    8447 non-null   int64
 236  R_ALL_STR_R5_LANDED       8447 non-null   int64
 237  R_ALL_STR_R5_ATTEMPTED    8447 non-null   int64
 238  B_ALL_STR_R5_LANDED       8447 non-null   int64
 239  B_ALL_STR_R5_ATTEMPTED    8447 non-null   int64
 240  R_SIG_STR_R4_LANDED       8447 non-null   int64
 241  R_SIG_STR_R4_ATTEMPTED    8447 non-null   int64
 242  B_SIG_STR_R4_LANDED       8447 non-null   int64
 243  B_SIG_STR_R4_ATTEMPTED    8447 non-null   int64
 244  R_HEAD_R4_LANDED          8447 non-null   int64
 245  R_HEAD_R4_ATTEMPTED       8447 non-null   int64
 246  B_HEAD_R4_LANDED          8447 non-null   int64
 247  B_HEAD_R4_ATTEMPTED       8447 non-null   int64
 248  R_BODY_R4_LANDED          8447 non-null   int64
 249  R_BODY_R4_ATTEMPTED       8447 non-null   int64
 250  B_BODY_R4_LANDED          8447 non-null   int64
 251  B_BODY_R4_ATTEMPTED       8447 non-null   int64
 252  R_LEG_R4_LANDED           8447 non-null   int64
 253  R_LEG_R4_ATTEMPTED        8447 non-null   int64
 254  B_LEG_R4_LANDED           8447 non-null   int64
 255  B_LEG_R4_ATTEMPTED        8447 non-null   int64
 256  R_DISTANCE_R4_LANDED      8447 non-null   int64
 257  R_DISTANCE_R4_ATTEMPTED   8447 non-null   int64
 258  B_DISTANCE_R4_LANDED      8447 non-null   int64
 259  B_DISTANCE_R4_ATTEMPTED   8447 non-null   int64
 260  R_CLINCH_R4_LANDED        8447 non-null   int64
 261  R_CLINCH_R4_ATTEMPTED     8447 non-null   int64
 262  B_CLINCH_R4_LANDED        8447 non-null   int64
 263  B_CLINCH_R4_ATTEMPTED     8447 non-null   int64
 264  R_GROUND_R4_LANDED        8447 non-null   int64
 265  R_GROUND_R4_ATTEMPTED     8447 non-null   int64
 266  B_GROUND_R4_LANDED        8447 non-null   int64
 267  B_GROUND_R4_ATTEMPTED     8447 non-null   int64
 268  R_SIG_STR_R5_LANDED       8447 non-null   int64
 269  R_SIG_STR_R5_ATTEMPTED    8447 non-null   int64
 270  B_SIG_STR_R5_LANDED       8447 non-null   int64
 271  B_SIG_STR_R5_ATTEMPTED    8447 non-null   int64
 272  R_HEAD_R5_LANDED          8447 non-null   int64
 273  R_HEAD_R5_ATTEMPTED       8447 non-null   int64
 274  B_HEAD_R5_LANDED          8447 non-null   int64
 275  B_HEAD_R5_ATTEMPTED       8447 non-null   int64
 276  R_BODY_R5_LANDED          8447 non-null   int64
 277  R_BODY_R5_ATTEMPTED       8447 non-null   int64
 278  B_BODY_R5_LANDED          8447 non-null   int64
 279  B_BODY_R5_ATTEMPTED       8447 non-null   int64
 280  R_LEG_R5_LANDED           8447 non-null   int64
 281  R_LEG_R5_ATTEMPTED        8447 non-null   int64
 282  B_LEG_R5_LANDED           8447 non-null   int64
 283  B_LEG_R5_ATTEMPTED        8447 non-null   int64
 284  R_DISTANCE_R5_LANDED      8447 non-null   int64
 285  R_DISTANCE_R5_ATTEMPTED   8447 non-null   int64
 286  B_DISTANCE_R5_LANDED      8447 non-null   int64
 287  B_DISTANCE_R5_ATTEMPTED   8447 non-null   int64
 288  R_CLINCH_R5_LANDED        8447 non-null   int64
 289  R_CLINCH_R5_ATTEMPTED     8447 non-null   int64
 290  B_CLINCH_R5_LANDED        8447 non-null   int64
 291  B_CLINCH_R5_ATTEMPTED     8447 non-null   int64
 292  R_GROUND_R5_LANDED        8447 non-null   int64
 293  R_GROUND_R5_ATTEMPTED     8447 non-null   int64
 294  B_GROUND_R5_LANDED        8447 non-null   int64
 295  B_GROUND_R5_ATTEMPTED     8447 non-null   int64
dtypes: bool(2), datetime64[ns](1), float64(48), int64(206), object(39)
memory usage: 19.0+ MB